from src.utils import init_args, update_config_files, get_most_recent_input_file
from dimlpfidex.fidex import fidexGloRules
from dimlpfidex.dimlp import dimlpBT
from trainings import normalization
from datetime import datetime
from src.patient import Patient
import src.data_helper as dh
from src.rule import *
import pandas as pd
import os


def write_patients(abspath: str) -> list[Patient]:
    # TODO: make it select the latest file inside the input/ directory
    input_file_path = get_most_recent_input_file(abspath)

    # TODO: check if read_excel is adapted
    metadata = pd.read_excel(
        input_file_path, index_col=False
    ).iloc[:, :5]
    clinical_data = dh.obtain_data(
        input_file_path, training=False
    )
    clinical_data = clinical_data.assign(
        BMI=lambda x: round(x.WEIGHT / (x.HEIGHT / 100.0) ** 2, 3)
    )

    patients = []
    for i in range(clinical_data.shape[0]):
        patients.append(Patient(metadata.iloc[i], clinical_data.iloc[i], abspath))

    return patients


# this is for testing puroposes only
def write_samples_file(abspath: str, n: int) -> list[Patient]:
    metadata = pd.read_excel(
        "input/PRE-ACT-01_Flow2_20241115_HES-SO.xlsx", index_col=False
    ).iloc[0, :5]
    data = pd.read_csv("temp/train_data.csv", sep=" ", header=None)

    sample_data = data.sample(n)

    print(metadata)
    print(sample_data)

    patients = []
    for i in range(n):
        metadata.iloc[3] = f"FRA_TEST_00{i+1}"  # FOR TESTING PURPOSES ONLY
        patients.append(Patient(metadata, sample_data.iloc[i, :], abspath))

    return patients


def write_attributes_file(attributes: list[str]) -> list[str]:
    attributes = attributes + ["LYMPHODEMA_NO", "LYMPHODEMA_YES"]

    with open("temp/attributes.txt", "w") as f:
        for attribute in attributes:
            f.write(attribute + "\n")

    return attributes


def write_train_data(data: pd.DataFrame, labels: pd.Series) -> None:
    labels = pd.get_dummies(labels).astype("uint")

    data.to_csv("temp/train_data.csv", sep=",", header=False, index=False)
    labels.to_csv("temp/train_classes.csv", sep=",", header=False, index=False)


def write_results(patients: list[Patient], attributes: list[str]) -> None:
    abspath = os.path.abspath(os.path.dirname(__file__))
    write_path = os.path.join(
        abspath, "output", f"results_{datetime.today().strftime('%Y%m%d')}.csv"
    )

    unicancer_headers = ["STUDYID", "SITEIDN", "SITENAME", "SUBJID", "VISIT"]
    rule_headers = ["RISK", "LOW_INTERVAL", "HIGH_INTERVAL", "RULE_ID"]
    headers = unicancer_headers + rule_headers + attributes

    string = ",".join(headers) + "\n"

    for patient in patients:
        string += patient.format_results()

    with open(write_path, "w") as fp:
        fp.write(string)


if __name__ == "__main__":
    args = init_args()
    abspath = os.path.abspath(os.path.dirname(__file__))

    data, labels = dh.obtain_data("dataset/clinical_complete_rev1.csv")
    data, labels = dh.filter_clinical(data, labels)
    # added BMI column
    data = data.assign(BMI=lambda x: round(x.WEIGHT / (x.HEIGHT / 100.0) ** 2, 3))

    nb_features = data.shape[1]
    nb_classes = 2

    attributes = write_attributes_file(data.columns.to_list())
    write_train_data(data, labels)

    if args.train:
        update_config_files(abspath, nb_features, nb_classes)
        normalization("--json_config_file config/train_normalization.json")
        dimlpBT("--json_config_file config/dimlpbt.json")
        fidexGloRules("--json_config_file config/fidexglorules.json")
        normalization("--json_config_file config/train_denormalization.json")
        exit()

    elif args.test:
        patients = write_samples_file(abspath, args.test)

    else:
        patients = write_patients(abspath)

    global_rules = GlobalRules.from_json_file("temp/global_rules_denormalized.json")

    for patient in patients:
        patient.extract_rules(global_rules)
        # TODO: find a way to test when rules are generated by fidex

    write_results(patients, attributes)
