from src.utils import init_args, update_config_files
from dimlpfidex.fidex import fidexGloRules
from dimlpfidex.dimlp import dimlpBT
from trainings import normalization
import src.data_helper as dh
from src.patient import *
from src.rule import *
import os

if __name__ == "__main__":
    args = init_args()
    abspath = os.path.abspath(os.path.dirname(__file__))

    data, labels = dh.obtain_data("dataset/clinical_complete_rev1.csv")
    data, labels = dh.filter_clinical(data, labels)
    # adding BMI column
    data = data.assign(BMI=lambda x: round(x.WEIGHT / (x.HEIGHT / 100.0) ** 2, 3))

    nb_features = data.shape[1]
    nb_classes = 2

    attributes = write_attributes_file(abspath, data.columns.to_list())
    write_train_data(abspath, data, labels)

    if args.train:
        update_config_files(abspath, nb_features, nb_classes)
        normalization("--json_config_file config/train_normalization.json")
        dimlpBT("--json_config_file config/dimlpbt.json")
        fidexGloRules("--json_config_file config/fidexglorules.json")
        normalization("--json_config_file config/train_denormalization.json")
        exit()

    elif args.test:
        patients = write_samples_file(abspath, args.test)

    else:
        patients = write_patients(abspath)

    print("Loading global rules...")
    global_rules = GlobalRules.from_json_file("temp/global_rules_denormalized.json")
    updated_global_rules = global_rules

    npatients = len(patients)
    print(f"Rule extraction is going to be performed on {npatients} patients")
    for i, patient in enumerate(patients):
        print(f"Extracting rules for patient {i+1}/{npatients}...")
        updated_global_rules = patient.extract_rules(updated_global_rules)
        print(f"Extraction done, {len(patient.selected_rules)} rules found")

    print(f"Rule extraction done for {npatients} patients")
    print(f"Writing UNICANCER results file...")
    write_results(abspath, patients, attributes)
    print(f"File successfully written")

    # save potentially generated rules if new ones appeared
    if len(updated_global_rules) > len(global_rules):
        # TODO: find a way to test when rules are generated by fidex
        difference = len(updated_global_rules) - len(global_rules)
        print(f"{difference} new rule(s) have been generated, saving...")
        updated_global_rules.save()

    print("Rule extraction program done")
